[project]
name = "tfg-query-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "asyncio>=3.4.3",
    "google-adk>=1.5.0",
    "google-genai>=1.23.0",
    "litellm>=1.73.6",
    "pip>=25.1.1",
]
